((:other-stack-matches
  ("flower" . #\⚘)
  )
 (:timeout . 750)
 (:keys
  (#\a (#\a "Open Front Vowel")
       (#\ɑ "Open Back Vowel")
       (#\æ "Near-Open Front Vowel")
       (#\ɐ "Near-Open Central Vowel")
       (#\ɒ "Rounded Open Back Vowel"))
  (#\b (#\b "Voiced Bilabial Plosive")
       (#\β "Voiced Bilabial Fricative")
       (#\ɓ "Voiced Bilabial Implosive")
       (#\ʙ "Bilabial Trill"))
  (#\c (#\c "Voiceless Palatal Plosive")
       (#\ɕ "Voiceless Alveo-Palatal Fricative")
       (#\ç "Voiceless Palatal Fricative"))
  (#\d (#\d "Voiced Alveolar Plosive")
       (#\ð "Voiced Dental Fricative")
       (#\ɖ "Voiced Retroflex Plosive")
       (#\ɗ "Voiced Alveolar Implosive"))
  (#\e (#\e "Close-Mid Front Vowel")
       (#\ə "Mid Central Vowel")
       (#\ɚ "Rhoticized Mid Central Vowel")
       (#\ɵ "Close-Mid Central Rounded Vowel")
       (#\ɘ "Close-Mid Central Vowel"))
  (#\3 (#\3 "Three (Not an IPA Character)")
       (#\ɛ "Open-Mid Front Vowel")
       (#\ɜ "Open-Mid Central Vowel")
       (#\ɝ "Rhoticized Open-Mid Central Vowel")
       (#\ɞ "Open-Mid Central Rounded Vowel"))
  (#\f (#\f "Voiceless labiodental fricative"))
  (#\g (#\ɡ "Voiced Velar Plosive")
       (#\ɠ "Voiced Velar Implosive")
       (#\ɢ "Voiced Uvular Plosive")
       (#\ʛ "Voiced Uvular Implosive"))
  (#\h (#\h "Voiceless Glottal Transition")
       (#\ɥ "Labial-Palatal Approximant")
       (#\ɦ "Voiced Glottal Fricative")
       (#\ħ "Voiceless Pharangeal Fricative")
       (#\ɧ "Sje-sound")
       (#\ʜ "Voiceless Epiglottal Fricative"))
  (#\i (#\i "Close Front Vowel")
       (#\ɪ "Near-Close Near-Front Vowel")
       (#\ɨ "Close Central Vowel"))
  (#\j (#\j "Palatal Approximant")
       (#\ʝ "Voiced Palatal Fricative")
       (#\ɟ "Voiced Palatal Plosive")
       (#\ʄ "Voiced Palatal Implosive"))
  (#\k (#\k "Voiceless Velar Plosive"))
  (#\l (#\l "Alveolar Lateral Approximant")
       (#\ɫ "Velarized Alveolar Lateral Approximant")
       (#\ɬ "Voiced Alveolar Lateral Fricative")
       (#\ʟ "Velar Lateral Approximant")
       (#\ɭ "Retroflex Lateral Approximant")
       (#\ɮ "Voiced Alveolar Lateral Fricative"))
  (#\m (#\m "Bilabial Nasal")
       (#\ɱ "Labiodental Nasal"))
  (#\n (#\n "Alveolar Nasal")
       (#\ŋ "Velar Nasal")
       (#\ɲ "Palatal Nasal")
       (#\ɴ "Uvular Nasal")
       (#\ɳ "Retroflex Nasal"))
  (#\o (#\o "Close-Mid Back Rounded Vowel")
       (#\ɔ "Open-Mid Back Rounded Vowel")
       (#\œ "Open-Mid Front Rounded Vowel")
       (#\ø "Close-Mid Front Rounded Vowel")
       (#\ɒ "Open Back Rounded Vowel")
       (#\ɶ "Open Front Rounded Vowel"))
  (#\p (#\p "Voiceless Bilabial Plosive")
       (#\ɸ "Voiceless Bilabial Fricative"))
  (#\q (#\q "Voiceless Uvular Plosive")
       (#\ʔ "Glottal Stop")
       (#\ʕ "Voiced Pharyngeal Fricative")
       (#\ʢ "Voiced Epiglottal Fricative")
       (#\ʡ "Epiglottal Plosive"))
  (#\r (#\r "Alveolar Trill")
       (#\ɾ "Alveolar Tap")
       (#\ʁ "Voiced Uvular Fricative")
       (#\ɹ "Alveolar Approximant")
       (#\ɻ "Retroflex Approximant")
       (#\ʀ "Uvular Trill")
       (#\ɽ "Retroflex Flap")
       (#\ɺ "Alveolar Lateral Flap"))
  (#\s (#\s "Voiceless Alveolar Sibliant")
       (#\ʃ "Voiceless Post-Alveolar Fricative")
       (#\ʂ "Voiceless Retroflex Fricative"))
  (#\t (#\t "Voiceless Alveolar Plosive")
       (#\θ "Voiceless Dental Fricative")
       (#\ʈ "Voiceless Retroflex Plosive"))
  (#\u (#\u "Close Back Rounded Vowel")
       (#\ʊ "Near-Close Near-Back Vowel")
       (#\ʉ "Close Central Rounded Vowel"))
  (#\v (#\v "Voiced Labio-Dental Fricative")
       (#\ʌ "Open-Back Mid Unrounded Vowel")
       (#\ʋ "Labiodental Approximant")
       (#\ⱱ "Labiodental Flap"))
  (#\w (#\w "Labio-Velar Approximant")
       (#\ʍ "Voiceless Labio-Velar Approximant")
       (#\ɯ "Close Back Unrounded Vowel")
       (#\ɰ "Velar Approximant"))
  (#\x (#\x "Voiceless Velar Fricative")
       (#\χ "Voiceless Uvular Fricative"))
  (#\y (#\y "Close Front Rounded Vowel")
       (#\ʎ "Palatal Lateral Approximant")
       (#\ɣ "Voiced Velar Fricative")
       (#\ʏ "Near-Close Near-Front Rounded Vowel")
       (#\ɤ "Close-Mid Back Vowel"))
  (#\z (#\z "Voiced Dental Fricative")
       (#\ʒ "Voiced Post-Alveolar Fricative")
       (#\ʐ "Voiced Retroflex Fricative")
       (#\ʑ "Voiced Alveo-Palatal Fricative"))))
